# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master
    
    #Environment variables
env:
  global:
    - GH_REPO_NAME: ONDA
    - DOXYFILE: $TRAVIS_BUILD_DIR/ONDA/.travis.yml
- GH_REPO_REF: github.com/Dan-escu/ONDA.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

